server:
  port: 8090
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
springdoc:
  swagger-ui:
    path: /doc
  packages-to-scan: com.hnlx.collegeinfo

# datasource is in nacos

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
